Fix: Messedup lines after change in H and V values
Fix: IndexError.

Traceback (most recent call last):
  File "/usr/share/sugar/activities/dotsAndBoxes.activity/main.py", line 366, in run
    ret = self.where(pos)
  File "/usr/share/sugar/activities/dotsAndBoxes.activity/main.py", line 211, in where
    b = self.boxes[x_b][y_b]
IndexError: list index out of range

To reproduce- Play a game half way and change V or H values, then try playing with changed grid. IndexError seen.